### ISSUE TITLE
Robots worktypes not properly scaled to robot tier.

### ISSUE THREAD

**Issue by BlakeTech** [alaestor/Rimworld-MiscRobotsPlusPlus#12]
Tailor, smith and oddly, craft, under WorkType, is showing up as with a proficiency of 3. There may be others that are specific to other bots, but this is, at least, true for the crafter bots.

This leads to the rather funny, if stupid, situation whereas a tier 5 crafter makes poor tailored products.

**Comment by JasperTecHK** [comment]
On further research, it seems to be not exactly a bug, more a missing feature, as vanilla expanded furniture's rugs use artistic for the product, which the robots do not have. So, there's a partial compatibility problem, instead of an outright bug.

**Comment by alaestor** [comment]
This is partly intentional because I originally intended robots to lack the Artistic skill. Though in retrospect, this may have been [a mistake](https://youtu.be/siHfHUm3HGE?t=99).
