### ISSUE TITLE
ER Bot

### ISSUE THREAD

**Issue by TheMunkeh** [alaestor/Rimworld-MiscRobotsPlusPlus#13]
Er bot does not do surgery. Previous versions of the game allowed it to do so, I cannot seem to get it to work.

**Comment by TheMunkeh** [comment]
Addition, I manually damaged one of my pawns through dev mode and it rescued the pawn but did no sort of healing.

**Comment by TheInfamousAlk** [comment]
I also have this issue. They will do no surgery or tending, with or without any kind of medicine. They feed, water (using water from bad hygiene), wash (again from bad hygiene), and rescue. But no tend or surgery. It is almost at the top of the load order.

**Comment by alaestor** [comment]
Can't replicate as of mv3.4.8 (for game version 1.4) so I'll assume it's fixed

**Comment by VeteranXT** [comment]
ER bots has priority of 1 for tending. So does Omni bots. In my game...200+ Mods i have no issue. Now this is what i look is try to replicate. 
So my suggestion proabably is some mod conflict.
How to find what mod? 
Disable 50% of all mods you currently have.
If problem exists. Its in enabled list.
if Problem fixed its in disabled list.
If you disabled 50% of your list and problem exists, cut another half. And try.
Same goes for Disabled.
You can narrow in matter of 30 mins what mod is causing conflict.

**Comment by energy11a** [comment]
One mod that I found to be causing an issue was QualitySurgeon. https://steamcommunity.com/sharedfiles/filedetails/?id=857350593

**Comment by VeteranXT** [comment]
I never used it, that's why i never had issues.
