### ISSUE TITLE
Robot loses power, stuck in sleep mode, does nothing

### ISSUE THREAD

**Issue by tungstenmeteor** [alaestor/Rimworld-MiscRobotsPlusPlus#32]
EDIT: Solved. I hadn't included the stove and butchering table in its zones. I am an idiot. Leaving this here for anyone else who has this problem, in case it helps you solve it too.

I'm able to direct control move it, but afterwards it just returns to the pad and sits there, in sleep mode.

While in sleep mode, it still loses power rather than gaining it. Reinstalling it can bring it to 100% but even then it will not operate.

This is only applicable to this one robot, recently bought from a trader. Others that were previously placed still seem to function normally.

![image](https://user-images.githubusercontent.com/45355413/207247432-4c48ad6b-92e6-4496-a61b-ecaeb2c5d08a.png)

**Comment by VeteranXT** [comment]
So this is not issue? It was on your end?

**Comment by VeteranXT** [comment]
This can't be fixed, its how its intended. This is form Misc.Robots type bug.
