### ISSUE TITLE
robots miss behaving after latest patch

### ISSUE THREAD

**Issue by AXB1466** [alaestor/Rimworld-MiscRobotsPlusPlus#6]
Hi the robots seem to be having issues no errors but the builders are just sitting their doing nothing and the others are barely doing anything and even the omni bot is not doing construction if the contents are not filled but the haulers are not pre filling construction jobs any more. It as if they lost the ability to due a lot of jobs.

**Comment by alaestor** [comment]
whoops...
should be fixed now. Please download the latest mv3.3.2
